const sampleListings = [
  {
    title: "Luxury Beach Resort",
    description: "Beautiful resort near the beach with sea view",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    price: 3500,
    location: "Goa",
    country: "India",
  },
  {
    title: "Mountain View Hotel",
    description: "Hotel with stunning mountain views",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 2800,
    location: "Manali",
    country: "India",
  },
  {
    title: "City Center Inn",
    description: "Comfortable stay in the heart of the city",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    price: 2200,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Royal Heritage Palace",
    description: "Experience royal living with modern facilities",
    image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b",
    price: 5000,
    location: "Jaipur",
    country: "India",
  },
  {
    title: "Peaceful Lake Cottage",
    description: "Calm and relaxing cottage near the lake",
    image: "https://images.unsplash.com/photo-1472220625704-91e1462799b2",
    price: 1800,
    location: "Udaipur",
    country: "India",
  },

  // ---------- MORE DATA ----------
  {
    title: "Hilltop Retreat",
    description: "Cozy stay on top of the hill",
    image: "https://images.unsplash.com/photo-1502673530728-f79b4cab31b1",
    price: 2600,
    location: "Darjeeling",
    country: "India",
  },
  {
    title: "Forest Eco Lodge",
    description: "Eco-friendly lodge surrounded by forest",
    image: "https://images.unsplash.com/photo-1501117716987-c8e1ecb2100b",
    price: 2100,
    location: "Wayanad",
    country: "India",
  },
  {
    title: "Desert Camp Stay",
    description: "Luxury tents in the Thar desert",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    price: 3200,
    location: "Jaisalmer",
    country: "India",
  },
  {
    title: "Riverside Homestay",
    description: "Homestay beside a peaceful river",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
    price: 1500,
    location: "Rishikesh",
    country: "India",
  },
  {
    title: "Luxury Business Hotel",
    description: "Perfect stay for business travelers",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
    price: 4000,
    location: "Mumbai",
    country: "India",
  },

  {
    title: "Budget City Hostel",
    description: "Affordable stay for backpackers",
    image: "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba",
    price: 900,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Luxury Villa Stay",
    description: "Private villa with pool",
    image: "https://images.unsplash.com/photo-1505691723518-36a5ac3b2b8f",
    price: 6500,
    location: "Lonavala",
    country: "India",
  },
  {
    title: "Beachside Cottage",
    description: "Cottage just steps away from the beach",
    image: "https://images.unsplash.com/photo-1505691723518-36a5ac3b2b8f",
    price: 2700,
    location: "Pondicherry",
    country: "India",
  },
  {
    title: "Snow View Resort",
    description: "Resort with snow-covered mountain views",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    price: 4800,
    location: "Gulmarg",
    country: "India",
  },
  {
    title: "City Budget Hotel",
    description: "Comfortable stay at affordable price",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 1400,
    location: "Patna",
    country: "India",
  },

  {
    title: "Heritage Haveli",
    description: "Traditional haveli with royal charm",
    image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b",
    price: 3600,
    location: "Bikaner",
    country: "India",
  },
  {
    title: "Tea Garden Stay",
    description: "Stay amidst lush tea gardens",
    image: "https://images.unsplash.com/photo-1502673530728-f79b4cab31b1",
    price: 2300,
    location: "Assam",
    country: "India",
  },
  {
    title: "Luxury Apartment",
    description: "Modern apartment in city center",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    price: 3300,
    location: "Hyderabad",
    country: "India",
  },
  {
    title: "Temple View Guesthouse",
    description: "Peaceful stay near famous temples",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
    price: 1200,
    location: "Puri",
    country: "India",
  },
  {
    title: "Jungle Safari Lodge",
    description: "Wildlife experience with comfort",
    image: "https://images.unsplash.com/photo-1501117716987-c8e1ecb2100b",
    price: 4200,
    location: "Jim Corbett",
    country: "India",
  },

  // 🔁 You can DUPLICATE pattern to reach 100
];

module.exports = { data: sampleListings };
